export async function main() {
  console.log("It runs!");
}

main().catch((err) => console.error(err));
